!!python/object:edges_estimate.likelihoods.MultiComponentChi2
_data: null
_data_seed: 3887866673
_name: lk
_store_data: false
components: !!python/tuple
- !!python/object:edges_estimate.foregrounds.LinLog
  _name: foregrounds
  components: !!python/tuple []
  derived: !!python/tuple []
  fiducial: !!python/object:frozendict.frozendict
    _dict: {}
    _hash: null
  freqs: &id004 !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 123
    - !!python/object/apply:numpy.dtype
      args:
      - f8
      - 0
      - 1
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      IeS8/4+XSUAh5Lz/j8lJQCHkvP+P+0lAIeS8/48tSkAh5Lz/j19KQCHkvP+PkUpAIeS8/4/DSkAh
      5Lz/j/VKQCHkvP+PJ0tAIeS8/49ZS0Ah5Lz/j4tLQCHkvP+PvUtAIeS8/4/vS0Ah5Lz/jyFMQCHk
      vP+PU0xAIeS8/4+FTEAh5Lz/j7dMQCHkvP+P6UxAIeS8/48bTUAh5Lz/j01NQCHkvP+Pf01AIeS8
      /4+xTUAh5Lz/j+NNQCHkvP+PFU5AIeS8/49HTkAh5Lz/j3lOQCHkvP+Pq05AIeS8/4/dTkAh5Lz/
      jw9PQCHkvP+PQU9AIeS8/49zT0Ah5Lz/j6VPQCHkvP+P109AEXLe/8cEUEARct7/xx1QQBFy3v/H
      NlBAEXLe/8dPUEARct7/x2hQQBFy3v/HgVBAEXLe/8eaUEARct7/x7NQQBFy3v/HzFBAEXLe/8fl
      UEARct7/x/5QQBFy3v/HF1FAEXLe/8cwUUARct7/x0lRQBFy3v/HYlFAEXLe/8d7UUARct7/x5RR
      QBFy3v/HrVFAEXLe/8fGUUARct7/x99RQBFy3v/H+FFAEXLe/8cRUkARct7/xypSQBFy3v/HQ1JA
      EXLe/8dcUkARct7/x3VSQBFy3v/HjlJAEXLe/8enUkARct7/x8BSQBFy3v/H2VJAEXLe/8fyUkAR
      ct7/xwtTQBFy3v/HJFNAEXLe/8c9U0ARct7/x1ZTQBFy3v/Hb1NAEXLe/8eIU0ARct7/x6FTQBFy
      3v/HulNAEXLe/8fTU0ARct7/x+xTQBFy3v/HBVRAEXLe/8ceVEARct7/xzdUQBFy3v/HUFRAEXLe
      /8dpVEARct7/x4JUQBFy3v/Hm1RAEXLe/8e0VEARct7/x81UQBFy3v/H5lRAEXLe/8f/VEARct7/
      xxhVQBFy3v/HMVVAEXLe/8dKVUARct7/x2NVQBFy3v/HfFVAEXLe/8eVVUARct7/x65VQBFy3v/H
      x1VAEXLe/8fgVUARct7/x/lVQBFy3v/HElZAEXLe/8crVkARct7/x0RWQBFy3v/HXVZAEXLe/8d2
      VkARct7/x49WQBFy3v/HqFZAEXLe/8fBVkARct7/x9pWQBFy3v/H81ZAEXLe/8cMV0ARct7/xyVX
      QBFy3v/HPldAEXLe/8dXV0ARct7/x3BXQBFy3v/HiVdAEXLe/8eiV0ARct7/x7tXQBFy3v/H1FdA
      EXLe/8ftV0ARct7/xwZYQBFy3v/HH1hAEXLe/8c4WEARct7/x1FYQBFy3v/HalhAEXLe/8eDWEAR
      ct7/x5xYQBFy3v/HtVhA
  nuc: 75.0
  params: !!python/tuple
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: &id002 !!python/tuple
    - null
    determines: !!python/tuple
    - p0
    fiducial: null
    latex: p0
    max: .inf
    min: -.inf
    name: p0
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 1750
      - 100
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - &id003 !!python/object/apply:numpy.random.__RandomState_ctor
          state: !!python/tuple
          - MT19937
          - !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 624
            - !!python/object/apply:numpy.dtype
              args:
              - u4
              - 0
              - 1
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              Vtxx55Uimxq7AbHqaVS9JyC3ykRVEy0T/vh3eHwP20OokQKheEVHJtvYbEXgFENW9xp/qTukWJss
              G9u/lJwdDex8pZ5bgnJN8IQDCSuYPRq1cjzjvoqhhh/iQj86+sq7seb+ODlt8AfsaljH9zn1PKUa
              NJRjDSrk1l1vID4jgjZwsKpKbQ5VKP4KTUnD0OZ+YImtzyst3x/M8lWTmYk6m6OjYJaCqOUcKooz
              /JSYrH9LmOXF+L15kjtwALrBAokSO2QrCyX3FbHyKWdT2nluCMqQacv++EgOqfMl4v22YAK9ROm2
              pOUxhzlFsFli5l3jy5NpsMAEamdzQrzkYZbDrlh1KPQUyPaJ50qendU3WJ7VmYZD00tcOFJq+ax9
              c5ZtNjljRiJ8b2PFRHTlCcQ97JyTZn40pNC5n0o9TmBQaYhWwUIAFSXzppHqyjtIzIXB6WK4kbeN
              w5VHjv9OJU2/dm0ahIrkaw7b8DdcCkL+v84HcEkjmsntLm8A9FI1a7gNrighFGLZxv0gzT/CIbOQ
              5KR/9cq6E88/TPO/+Zrqx5wvBXJW9i/yqHtgR46qrqE42/6Wg+YpOqNDamQ01HdBiBClP9fsbTNa
              b87rjoMUNtG9HYKNgagCYkx1Cuz/FA0t9ZqrXan4dmLzcfjpxOMakbxkHKNtEREpeQA/XDQhHtp4
              0IvqDFEbOy9di2l9K6TKR5FyvIDOvz3FXn+WRg4gzqOipDg83FYzg6NQ5MoCB58nOzqu95HPR90T
              uWHsKhnWDLTAaxuE8HucG9vXqctKceMzEzt2+ogD5U4gvIRwSf7vgN6/db0QJKSHkFSH9slAKUIL
              cyOgojfyTcKiWGJbPBZT9gZ92THXGZwPMCY9Hfiiyz7H1opWZxYLmhLAsqHwe0MFGnmEIS67gcGO
              wIIEQSd/O5AIbTDw5hGHyVMG1YlAsG0EGTYexGXTspGicwn/YTk+pgtBXyBI8SIugud6vKP5g34V
              NDw99LcVSRXI4sRs6cg6kTd7u6dclp7FJd4GzgppLQx9FZ1YkElBdCJYX2ldeiAOV5qGHGKWP1dn
              9iCmvU38wYldXTdsV5685usUhY16YC6qYs41gzSl8PppWqa4EezH6wkmOg2wB6HIxfQZpyb4agP+
              zG5qEm7acpW5ssH3pRnMwrr69Zk4jZAbflXWMSoVMs5ylGpbdPwUu2ZeQh1H7AykBhNUx1Uh+IEz
              pMIqnJwU6cuw4+8zy0GhInmlIxHemXyFnfMf4NzltSDtZVgACUQKx4gvqhTj2o2Qz3cF8TDqNS8F
              f3BS3Kizhd1BPR0OkRDDUvtLRFnTeLbIPTZcMNotUEfdXerqk63YIHs4iUgYLbdSEb7DpjKY5wS0
              XJC5z8JcuvbsoKOKtV51t609IG7yuDxK8NHxMIt7MIFTx6VcUppqJov7WaZ5hOFR63Y4zIfq32Uy
              wBPJSS/8rOcLUke8WvKqfSRC4do+JxJ3xLoMXRnhLkO1BSKFPNToac5Fp6EvhUHghWI4zDuiVH/U
              xwzsDQk32XHjj/9LJl5MmjpzqDyPg/vp+FN5J3R1MVAZcZuCgILazgGXV0G9smcdc6C+AEIzYPqo
              DkDrTqn4pQ4uEb9RHJZI0bOU27MB8d9dtLWJ/wjGSuqwQVgkTRZjMp0/7IDDiXNRj5da1B7KwbK7
              YlAhI8aiDI034BNsMc0qm6Nv+eeev+OuTy7LLiUVEvE3cgmgyB5DoI0JmdwV6hUp4LGTTnOhvsjp
              tvV15A/miJ8dmhVNAC6ViNNu9rz24+Yc64imev6VyvI2+TawOopZXLTVaIn+LN2UuyqRzgwdcAUN
              /2WFmUy6wvwRqra+QNp+9a6bCeJ8pEv4ByLbzV5GQJGRxpyyr0v0no+IcCiNFnkPN4AwyNncSGfu
              mhrFi3surzcnziMCc6WTUdaBy7bSkjq560ejHXzt94EZBekFAXVCBJgaWFZN5VK0L49UIOK+hQDb
              AIBh9Q6Gezs4EKHrM6sAeEHy+DURNEGIsrrrjFITZgwKZKpa0cscVLZQRWz2h6dEdtu4vql77SP2
              j5pXImcYD5JvBYb3TW8b2nzedzKiJ/q694NaqW1qJbE9Lbk0jSeF3QVgSaxNyCG1bknuOJzmtI5Y
              pAh52v7NCisvIzUbGmV1T6qEL03sQlSZeaIAgoFX2wh1z5WGNeoQB6hFV0u7zlZHGR4PxptLdjvj
              15Dkmy+D3LEFiBacPxY9Uj+ZxCvYED51vV/zXBobMtBvhk8zBM61YIg5T3lILjqyxta3jQZUPMnL
              NVs8V+wXPLqLzAKbeLAT2kvA00Ku0SfdZIjTQO16WVHh2eYV9+TCKMzYEV6ns0C/z1oszNFb0xoN
              joN8dCAHh+ZWRAO41/T9Ljp/5ZwuYNOx8Z/YFJGm6CUCumj3JLdAJ6uDuWm1BR8Ejs1NvSjvkGRu
              gqD11lX8AOoo3VpmuUTUJaT5MTK+TXteeGf1GStUOapiZwUtRaU8M8L7VOKqb5IRbGcnqTcagRFx
              8xmeMDVHn/+sTlBXypy84QfQIhp7BRZYZdYEYhboM9AcAxKiU0AMoNuahnh0wAVViQgdPNeibUUS
              go2Z3Q8d8pLUFTmrQJAuslZ3nEXFM6Xpat5uFmAkrSVFNV08lU60u1MRjXzRikHRdkIJymh9ai9L
              GEiVLYuqurqqmT9gZOOKdaUa5OgYvOo5uTrZGJ0ABJZqUNKWHS6fp5Ja70C+GlaHOnAKtVUUBGHU
              nr7xD9Fi4DFfmLb8OMtxiasFp83duvJuejdzqKlsmKuUGHR5b0nyibOo846qp96WebnN73FylXMY
              B6MjRvkR4Ge24Lwg1T8XWweRwFRfklzOnTNAXKUj6Ag/PmJPCHfeTVLH6vHUkEQcVZCLYXTj5taD
              rGadVBxCuoCkkmE+u3Xjq3xzBu6YqPvfk2IzIdxK8ceLo1It3abj58THu0f27iTiotalfB4Z+YZx
              rvQ9gIsElC//DMz/Kf/NtHBTNKADGS26b5YbKvJXvm/zCAZ8B2qdrV2CNXPdi0mz1UR2JLxFOlOG
              8FgDM6bKjBcsQ3F3Jj89VO/eBX6472pxWdVrSkV6UsUkMlNQz4319cJFCLYDT1uM4v4jkq1e97FA
              FzYUfnQ5YhGqwwHuDKgrmbA2a+Npsh8Y0YX6rs5TDMW7xJZQLodv7AufSHoxL5y/r7OLWXnWsRwr
              KS/LBiqmRDVjw7EoU57Rqg9GcdXw24hn+zMewhec+gfe8u8mYMfcAnuJsgtjG9gnMVEWvbuXIJVc
              locKHCSwyqPlZetOH1YODELKdVcvYAbvYd04R9we9NmYVzzrzQTaUv7jzw1d
          - 52
          - 0
          - 0.0
      kwds: {}
    ref: null
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: *id002
    determines: !!python/tuple
    - p1
    fiducial: null
    latex: p1
    max: 1000.0
    min: -1000.0
    name: p1
    prior: null
    ref: null
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: *id002
    determines: !!python/tuple
    - p2
    fiducial: null
    latex: p2
    max: .inf
    min: -.inf
    name: p2
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 0
      - 200
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    ref: null
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: *id002
    determines: !!python/tuple
    - p3
    fiducial: null
    latex: p3
    max: .inf
    min: -.inf
    name: p3
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 0
      - 200
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    ref: null
  poly_order: 4
- !!python/object:edges_estimate.eor_models.AbsorptionProfile
  _name: AbsorptionProfile
  components: !!python/tuple []
  derived: !!python/tuple []
  fiducial: !!python/object:frozendict.frozendict
    _dict: {}
    _hash: null
  freqs: *id004
  params: !!python/tuple
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: *id002
    determines: !!python/tuple
    - A
    fiducial: null
    latex: A
    max: .inf
    min: -.inf
    name: A
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 0.5
      - 0.04
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: *id002
    determines: !!python/tuple
    - nu0
    fiducial: null
    latex: nu0
    max: .inf
    min: -.inf
    name: nu0
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 78.0
      - 1.0
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: *id002
    determines: !!python/tuple
    - tau
    fiducial: null
    latex: tau
    max: .inf
    min: -.inf
    name: tau
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 7
      - 1
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
  - !!python/object:yabf.core.parameters.Param
    _parameter_mappings: *id002
    determines: !!python/tuple
    - w
    fiducial: null
    latex: w
    max: .inf
    min: -.inf
    name: w
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 18
      - 4
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    ref: null
derived: !!python/tuple []
fiducial: !!python/object:frozendict.frozendict
  _dict: {}
  _hash: null
kind: spectrum
params: !!python/tuple
- !!python/object:yabf.core.parameters.Param
  _parameter_mappings: *id002
  determines: !!python/tuple
  - sigma
  fiducial: null
  latex: sigma
  max: .inf
  min: -.inf
  name: sigma
  prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
    a: -.inf
    args: !!python/tuple
    - 0.2
    - 0.05
    b: .inf
    dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
      state: !!python/tuple
      - a: -.inf
        b: .inf
        badvalue: .nan
        extradoc: null
        longname: null
        momtype: 1
        name: norm
        seed: null
        shapes: null
        xtol: 1.0e-14
      - *id003
    kwds: {}
  ref: null
sigma: null
