!!python/object:edges_estimate.likelihoods.MultiComponentChi2
_data: null
_data_seed: 1564009961
_name: lk
_store_data: false
components: !!python/tuple
- !!python/object:edges_estimate.foregrounds.LinLog
  _name: foregrounds
  components: !!python/tuple []
  derived: !!python/tuple []
  fiducial: !!python/object:frozendict.frozendict
    _dict:
      beta: -2.45
    _hash: null
  freqs: &id005 !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id002 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 123
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - 0
      - 1
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      IeS8/4+XSUAh5Lz/j8lJQCHkvP+P+0lAIeS8/48tSkAh5Lz/j19KQCHkvP+PkUpAIeS8/4/DSkAh
      5Lz/j/VKQCHkvP+PJ0tAIeS8/49ZS0Ah5Lz/j4tLQCHkvP+PvUtAIeS8/4/vS0Ah5Lz/jyFMQCHk
      vP+PU0xAIeS8/4+FTEAh5Lz/j7dMQCHkvP+P6UxAIeS8/48bTUAh5Lz/j01NQCHkvP+Pf01AIeS8
      /4+xTUAh5Lz/j+NNQCHkvP+PFU5AIeS8/49HTkAh5Lz/j3lOQCHkvP+Pq05AIeS8/4/dTkAh5Lz/
      jw9PQCHkvP+PQU9AIeS8/49zT0Ah5Lz/j6VPQCHkvP+P109AEXLe/8cEUEARct7/xx1QQBFy3v/H
      NlBAEXLe/8dPUEARct7/x2hQQBFy3v/HgVBAEXLe/8eaUEARct7/x7NQQBFy3v/HzFBAEXLe/8fl
      UEARct7/x/5QQBFy3v/HF1FAEXLe/8cwUUARct7/x0lRQBFy3v/HYlFAEXLe/8d7UUARct7/x5RR
      QBFy3v/HrVFAEXLe/8fGUUARct7/x99RQBFy3v/H+FFAEXLe/8cRUkARct7/xypSQBFy3v/HQ1JA
      EXLe/8dcUkARct7/x3VSQBFy3v/HjlJAEXLe/8enUkARct7/x8BSQBFy3v/H2VJAEXLe/8fyUkAR
      ct7/xwtTQBFy3v/HJFNAEXLe/8c9U0ARct7/x1ZTQBFy3v/Hb1NAEXLe/8eIU0ARct7/x6FTQBFy
      3v/HulNAEXLe/8fTU0ARct7/x+xTQBFy3v/HBVRAEXLe/8ceVEARct7/xzdUQBFy3v/HUFRAEXLe
      /8dpVEARct7/x4JUQBFy3v/Hm1RAEXLe/8e0VEARct7/x81UQBFy3v/H5lRAEXLe/8f/VEARct7/
      xxhVQBFy3v/HMVVAEXLe/8dKVUARct7/x2NVQBFy3v/HfFVAEXLe/8eVVUARct7/x65VQBFy3v/H
      x1VAEXLe/8fgVUARct7/x/lVQBFy3v/HElZAEXLe/8crVkARct7/x0RWQBFy3v/HXVZAEXLe/8d2
      VkARct7/x49WQBFy3v/HqFZAEXLe/8fBVkARct7/x9pWQBFy3v/H81ZAEXLe/8cMV0ARct7/xyVX
      QBFy3v/HPldAEXLe/8dXV0ARct7/x3BXQBFy3v/HiVdAEXLe/8eiV0ARct7/x7tXQBFy3v/H1FdA
      EXLe/8ftV0ARct7/xwZYQBFy3v/HH1hAEXLe/8c4WEARct7/x1FYQBFy3v/HalhAEXLe/8eDWEAR
      ct7/x5xYQBFy3v/HtVhA
  nuc: 75.0
  params: !!python/tuple
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - p0
    fiducial: 7.4673710669175595
    latex: \log p_0
    max: 7.600902459542082
    min: 7.313220387090301
    name: logp0
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          ugdehZbeHUA=
      - 0.02
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - &id003 !!python/object/apply:numpy.random.__RandomState_ctor
          state: !!python/tuple
          - MT19937
          - !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id002
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 624
            - !!python/object/apply:numpy.dtype
              args:
              - u4
              - 0
              - 1
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              XZCf/gWMoqAmhsLgdpdi7UJsdIkB3ZJNSQ8sA6MfYTQUybHzWcr9DMBlxN/JiJTwfEAhMqCOlz7v
              eQMnpgTVY3ewOzM3HArqMnQM52yJ0N5/Cr4KQTUoxtVMM5SaVDmpOiqEbUW6EAxUdBmTh/eV+BXd
              kWeCvhaialWnVDZwJGoOltvV8Y72CiZHmoTaJqSBUzsftF2fM/2Sm8rIAejqMxyfaobWxbVV/dLq
              dRJ5HOqAjGGpJX3bP691EzOvO204Oz5Dua1QDd0nbT0GVv0a/qNx0kWdF9XHtP2lgRmCWqDShSP5
              rn+0FGmWvlLoKazjbbVhX9M2QjPYAk/RFImMjimKPazXDWfUZW7r6WteKprPw0eW+4FRhFBGalOH
              Y0fLaqHLYMB6cBrVVQdLdLsByicPqJP+HNBZ1lQYamkP2P9Xg6gJlMNKdft2hj5/Xy5ABUJLWLrV
              AotovOyhpohHcxpViId99GyTvOe2aeyRDPXbQE4XyB5dmqv96PJasDTSXvLTiG3lWk6G0jcndDQZ
              FNlbEiT4nG1cM8R50fOX4IccjNELHLqGtahKFigbNXdiYmtdkKtVBS6cPlilVG//xhG4USWs2KlD
              TMeGIi03Aa3C7q5UzvKxk3Nr7EQVtlefk+yUOKvZp5IxGGV6XRVCX/6uAOLF1uBlndaZoN6V+KTa
              yAZg9q3Oy+gUNL+F68besh5Qhx6ZBLJCbRS0BSszHvkS9HJwr6Ms6MjnT2xr5vf03pOc3VT0zL0T
              sIexXyD2WOZhv7AHi1KiumAJuweq1GNtRD5Ts+BBjU8rVieLT9xTPLahxBqn2RSSJ5aKpJRNTg44
              xdcSys5tlXt+WXXODttxEpZUa6n82lJm9XrLEndbtm6sui/3PGYLV9p1Y9CskgpsZfqLF3cOomHG
              AgC6/lHjR65XWvPucefqXF2M6+wzXm1EkO7JzqN14WXrfKhHj1fhtznby02HZlt3G0oM1zHTU9uB
              TPDvP0wjgBSn/c5TcRw8ovsDvXAFdvatUaTm/6Zbw+80NQrlUeNDT/16lNxIkM0boW3ud4hYCc4+
              e9ndonhnsCu93pqqPQYLxTFXaZAYX1aLi57zfM8zvRxxgfNh6gby3JOWLZZqrcjbR0CrRF9TIlKc
              JKvnu2rPLfOMu44s0LY6FtdVvqnh0IUekFzIy4qVEFOh5rbagWWvaO+FuSRVySCaxnLDlXeyP2gc
              dJlL8wy4Wm+ZRnyGe6zUPI+zIKvqBk98cgW7MPltmQ/F1ZDJB6x9q7vdqALJ6m5vM+s714pusO3P
              rYoK5m8jU6dMrFkQVcZZz9ZbbluKn2Ti93bosq2G45T8+alXbq0PtpTfv/8OdXh/5tgYg45GXvV9
              Saku2YGOiiIrBbtShX4XAQml4Rvo7fgkGnmgvOBJK60RnCMU3xkORAFDEiOq0MkpIHLGS/ze7lj8
              9gGFv502PvpD6W/VrXYURYrDCYZjykYXrDFxP3Jtrh/6mFD8ZP3MVdCASmQtiZMlt/LwDNHAeEu5
              baCkS3TFSf6rLB5fmCNmgrAXz5oL7Fw8tp71lS4Bcrdn621wHf/CyEV1U/zAm8KlfoDhGacc9Ern
              g+WLTsqapEUZek70VkqjWk283I397giBrtpiqY2zNoUumJ9OJo5z6WQVc9BkzUtljKfDdPuchI5q
              sRfmQN0vibWhYk4aSXxI542yRwedzTbYyRVJcT82rdVKjKrKYAGNsu/V6W+4ZZUT1WnC5YxcFAdC
              wD9/QoqepqzYXmWL24IpjJ469aPMG5oawFuzjGMh98jE0NYrVzq5TPIhBFHSON8dSqw+AJ2ecc4H
              NyYh4NYaSEUOx3FW2K0bWlci93njelCQzZtLi4jir2sDgIL5VQsJpsO1z0a2EH5Stu1/mkKrXzW+
              8FFIIj+5EATmRJlohxuTgHMMWDj9RYxpAdu7G5rin0HeJ+QL3y1Xmm4ZUwfLLckk3oABCA2E5fvz
              jAILV35h6WmHMglSldH4MmabFdh2zLbRaxLM8g3gwjlll5h8uSfQyZpWaPhAFwuE04a+5wlOeJwi
              NhAX8uRnYGHojZ8lt+KBxQnTdWsG4qIgB4NeINLEr65gTimD1YvLLhu0+dQRmZOvqhZxC4j6q5n3
              cooZ+IHFgvjP7nnYizdaRhLAho36MOW3MrmryBCGLZ9ZK4zRRRe0wcdpINlT5mn/zGlrnlgMn8Wz
              krx3uAEGvAEnAbH1Ay7IR3AdTEWabCtZDDftbNGY9k2QaU9vHKgwUWoGfqxhqVDyLuSbvWMssnBT
              2Ljz3EGw6vfIfb2uibGiqcS11Yt6p8UMPTP6hIaDFs8caJNDP8PNgHG4/xWyvezt5AWeLfwgaJV/
              BTzHW1iyAHMMYWeI0jvO2fSKmzkPYXArIJwD6bwSXicdqRu5k0bS2+8hi2aSBts2hheo9KVKpHAA
              iOoogeXW+5UymBN7pFexMGoB2MTJU/TOtYbqGlKsC4FzNKguQMBIFRtuSi+XLzEUGiILmCycBxqy
              muvk/otHM7GGv/I9GxNzsGoIwcSj1Xu4is553LIDdKF4BRsZFdE/m9MGXCPQiuxBS8phWdRb1lic
              AoUH92sW+yYrGmecXIYzgdjsihKSqkS5davp8Kxcia53w1Ezmz85G+c93c8OTeqE0ZQ/yWc1sO6P
              ONcuUnOQo1+8DGjOO/eAeF9yORCyWAbmkHCKkhWiL95aOOhBkcTkncLsmA2ytFQ1EMJnl9TaTrWM
              0EEf4sWpvnuvTKl5ahiMG+Ej9t9OgWQjPLOzjaKTA/SdoUm0sV6gCUAB1raaazkkCv0YbNu3nW1x
              k/P+YybjTJhbuCWTlt+xU4PKjzLhj5ozJLiz5PmwY13PSQrGLpH/Y0yafIrNemuyIxjEWRmHz7l4
              zHBx4xJ4BQTRm8ullo3yBp1XIAzO+KLdtuaBCGKv+LNIYy7YVAnW0DNxN0sS57ssIf/CsBTcJkxK
              CX/mDKnDHTOSaF4cBi0px7mCOTcNdiRfufBRaem+eveqyoSvh/+PTKXnv+TWnfnp/SCWgK5EzIBF
              mgMve7n9lu6xXGfNqUaiYP2Tlsr4ztClPaEsq5TXIw5lNivjEcpmLh0fnQmkfuqUkO97/h4AMfFb
              bSi7vJ9H+3+CkeHoHb/heGwAGouKmb/Fe+wosrS1wz95TZHjkkPLEEavX0ok17WBAmF3Kook/rsA
              c4ShOjRcZ7Oqg4ER5avhzXkh8yNc0b8ugwhTVyalYmE2YghWQv/m1N23JgluhK8OvgSETQuxOtTa
              3T5VhHGSsebgBuE4q9EImL1ohSm/N/ejRZv0G0fegHfVTGShDco+TZto6+gM
          - 436
          - 0
          - 0.0
      kwds: {}
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          ugdehZbeHUA=
      - 0.01
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    transforms: !!python/tuple
    - !!python/object/apply:numpy.core._ufunc_reconstruct
      - numpy
      - exp
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - p1
    fiducial: null
    latex: p1
    max: 1000.0
    min: -1000.0
    name: p1
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 0
      - 100
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    ref: null
    transforms: &id004 !!python/tuple
    - null
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - p2
    fiducial: null
    latex: p2
    max: 1000.0
    min: -1000.0
    name: p2
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 0
      - 100
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    ref: null
    transforms: *id004
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - p3
    fiducial: null
    latex: p3
    max: 1000.0
    min: -1000.0
    name: p3
    prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 0
      - 100
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    ref: null
    transforms: *id004
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - beta
    fiducial: 2.5
    latex: beta
    max: 2.7
    min: 2.3
    name: beta
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 2.5
      - 0.01
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    transforms: !!python/tuple
    - !!python/name:__main__.%3Clambda%3E ''
  poly_order: 4
- !!python/object:edges_estimate.eor_models.AbsorptionProfile
  _name: AbsorptionProfile
  components: !!python/tuple []
  derived: !!python/tuple []
  fiducial: !!python/object:frozendict.frozendict
    _dict: {}
    _hash: null
  freqs: *id005
  params: !!python/tuple
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - A
    fiducial: null
    latex: A
    max: 2.0
    min: -.inf
    name: A
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 0.5
      - 0.05
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    transforms: *id004
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - nu0
    fiducial: null
    latex: nu0
    max: 90.0
    min: 60.0
    name: nu0
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 78
      - 1
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    transforms: *id004
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - tau
    fiducial: null
    latex: tau
    max: 12.0
    min: 3.0
    name: tau
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 7
      - 0.5
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    transforms: *id004
  - !!python/object:yabf.core.parameters.Param
    determines: !!python/tuple
    - w
    fiducial: null
    latex: w
    max: 30.0
    min: 10.0
    name: w
    prior: null
    ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
      a: -.inf
      args: !!python/tuple
      - 17
      - 1
      b: .inf
      dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
        state: !!python/tuple
        - a: -.inf
          b: .inf
          badvalue: .nan
          extradoc: null
          longname: null
          momtype: 1
          name: norm
          seed: null
          shapes: null
          xtol: 1.0e-14
        - *id003
      kwds: {}
    transforms: *id004
derived: !!python/tuple []
fiducial: !!python/object:frozendict.frozendict
  _dict: {}
  _hash: null
kind: spectrum
params: !!python/tuple
- !!python/object:yabf.core.parameters.Param
  determines: !!python/tuple
  - sigma
  fiducial: 0.02
  latex: sigma
  max: 0.5
  min: 0.005
  name: sigma
  prior: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
    a: -.inf
    args: !!python/tuple
    - 0.02
    - 0.005
    b: .inf
    dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
      state: !!python/tuple
      - a: -.inf
        b: .inf
        badvalue: .nan
        extradoc: null
        longname: null
        momtype: 1
        name: norm
        seed: null
        shapes: null
        xtol: 1.0e-14
      - *id003
    kwds: {}
  ref: !!python/object:scipy.stats._distn_infrastructure.rv_frozen
    a: -.inf
    args: !!python/tuple
    - 0.02
    - 0.001
    b: .inf
    dist: !!python/object/new:scipy.stats._continuous_distns.norm_gen
      state: !!python/tuple
      - a: -.inf
        b: .inf
        badvalue: .nan
        extradoc: null
        longname: null
        momtype: 1
        name: norm
        seed: null
        shapes: null
        xtol: 1.0e-14
      - *id003
    kwds: {}
  transforms: *id004
sigma: null
